"""Merge the FITme Ayurveda iOS module into ONE Swift file: fitme-ios/FITmeAyurveda.swift.

The three JSON resources are embedded as raw string literals, so the app needs no
bundled resources. SwiftUI screens are wrapped in `#if canImport(SwiftUI)` so the same
file also compiles (and is tested) on Linux.

Run after build_ios_data.py.
"""
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
IOS = os.path.join(os.path.dirname(HERE), "fitme-ios")
SRC = os.path.join(IOS, "Sources")
RES = os.path.join(IOS, "Resources")
DELIM = "####"


def body(path):
    """Swift source without its import lines (the merged file imports once)."""
    text = open(path, encoding="utf-8").read()
    return re.sub(r"^import \w+\n", "", text, flags=re.M).strip() + "\n"


def embedded(name):
    raw = open(os.path.join(RES, name), encoding="utf-8").read()
    json.loads(raw)  # fail early on bad JSON
    assert f'"{DELIM}' not in raw, "raw string delimiter collides with data"
    return raw


def main():
    data_src = body(os.path.join(SRC, "AyurvedaData.swift"))
    # Default init reads the embedded JSON instead of bundle resources.
    data_src = data_src.replace(
        "    init(bundle: Bundle = .main) throws {",
        "    /// Loads the JSON embedded at the bottom of this file. No bundle resources needed.\n"
        "    init() throws {\n"
        "        try self.init(otcData: Data(EmbeddedAyurvedaJSON.otc.utf8),\n"
        "                      herbData: Data(EmbeddedAyurvedaJSON.herbs.utf8),\n"
        "                      medicineData: Data(EmbeddedAyurvedaJSON.medicines.utf8))\n"
        "    }\n\n"
        "    init(bundle: Bundle) throws {", 1)
    assert "EmbeddedAyurvedaJSON.otc" in data_src

    out = f"""// FITmeAyurveda.swift
// One-file FITme Ayurveda module: models, data layer, SwiftUI screens and all data.
//
// HOW TO USE
//   1. Drag this file into Xcode (tick "Copy items if needed" and your app target).
//   2. Show it, e.g. as a tab:
//        AyurvedaHomeView()
//            .environmentObject(AyurvedaStore())
//            .tabItem {{ Label("Ayurveda", systemImage: "leaf") }}
//   Requires iOS 16+. Works offline; no network calls.
//
// DATA (embedded at the bottom of this file)
//   - 15 everyday complaints, 168 classical Ayurvedic options (Ministry of AYUSH
//     Ayurvedic Standard Treatment Guidelines, 2017), English + Hindi
//   - 113 herbs / formulations / bhasmas with safety flags and medicine interactions
//   - 2,626 medicines with aliases for search and label scanning
//
// Generated by fitme-ayurveda-data/build_ios_single_file.py. Edit the sources and
// regenerate rather than editing the embedded JSON by hand.
//
// General safety information only, not medical advice.

import Foundation
#if canImport(SwiftUI)
import SwiftUI
#endif

// MARK: - ======================== Models ========================

{body(os.path.join(SRC, "AyurvedaModels.swift"))}
// MARK: - ======================== Data layer ========================

{data_src}
// MARK: - ======================== SwiftUI screens ========================

#if canImport(SwiftUI)
{body(os.path.join(SRC, "AyurvedaViews.swift"))}#endif

// MARK: - ======================== Embedded data ========================

enum EmbeddedAyurvedaJSON {{
    static let otc = {DELIM}\"\"\"
{embedded("AyurvedaOTC.json")}
\"\"\"{DELIM}

    static let herbs = {DELIM}\"\"\"
{embedded("HerbSafety.json")}
\"\"\"{DELIM}

    static let medicines = {DELIM}\"\"\"
{embedded("Medicines.json")}
\"\"\"{DELIM}
}}
"""
    path = os.path.join(IOS, "FITmeAyurveda.swift")
    with open(path, "w", encoding="utf-8") as f:
        f.write(out)
    print(path, f"{os.path.getsize(path) / 1024:.0f} KB")


if __name__ == "__main__":
    main()
