"""Devanagari names for the Ayurvedic OTC options file (used by build_ios_data.py).

Classical formulation names follow the usual Hindi/Sanskrit spelling found on
Indian product labels. Have a native reader skim these before release.
"""

COMPLAINTS_HI = {
    "Acidity / heartburn after meals": "एसिडिटी / खाने के बाद सीने में जलन",
    "Occasional constipation": "कभी-कभी कब्ज़",
    "Loose motions (mild, adults)": "हल्के दस्त (वयस्क)",
    "Cough (short-term)": "खांसी (कुछ दिनों की)",
    "Common cold: runny or blocked nose, sneezing": "सर्दी-जुकाम: बहती या बंद नाक, छींक",
    "Occasional tension-type headache": "कभी-कभी तनाव वाला सिरदर्द",
    "Occasional lower-back stiffness or ache": "कभी-कभी कमर में जकड़न या दर्द",
    "Occasional joint stiffness (massage oils)": "कभी-कभी जोड़ों में जकड़न (मालिश तेल)",
    "Occasional trouble sleeping": "कभी-कभी नींद न आना",
    "Mouth ulcers (minor)": "मुंह के छाले (हल्के)",
    "Intestinal worms (adults)": "पेट के कीड़े (वयस्क)",
    "Piles discomfort": "बवासीर की तकलीफ़",
    "Shoulder stiffness": "कंधे में जकड़न",
    "Period cramps": "मासिक धर्म का दर्द",
    "Gum care (sore or swollen gums)": "मसूड़ों की देखभाल (दर्द या सूजन)",
}

OPTIONS_HI = {
    "Abhayarishta": "अभयारिष्ट",
    "Agastya haritaki": "अगस्त्य हरीतकी",
    "Amalaki churna": "आमलकी चूर्ण",
    "Anu taila": "अणु तैल",
    "Aragvadha churna": "आरग्वध चूर्ण",
    "Ashwagandha balalakshadi taila": "अश्वगंधा बलालाक्षादि तैल",
    "Ashwagandha churna": "अश्वगंधा चूर्ण",
    "Ashwagandha churna with Pippalimoola churna": "अश्वगंधा चूर्ण के साथ पिप्पलीमूल चूर्ण",
    "Ashwagandhadi churna (with milk at bedtime)": "अश्वगंधादि चूर्ण (रात को दूध के साथ)",
    "Ashwagandharishta": "अश्वगंधारिष्ट",
    "Avipattikara churna": "अविपत्तिकर चूर्ण",
    "Bala churna": "बला चूर्ण",
    "Bala taila": "बला तैल",
    "Balarishta": "बलारिष्ट",
    "Bharangyadi avaleha": "भार्ङ्ग्यादि अवलेह",
    "Bibhitaki churna with Pippali churna": "बिभीतकी चूर्ण के साथ पिप्पली चूर्ण",
    "Bibhitaki kwatha": "बिभीतकी क्वाथ",
    "Bilwadi gutika": "बिल्वादि गुटिका",
    "Bilwamoola churna": "बिल्वमूल चूर्ण",
    "Brahmi ghrita (nasal drops)": "ब्राह्मी घृत (नाक में बूंदें)",
    "Bruhat Gangadhara churna": "बृहत् गंगाधर चूर्ण",
    "Castor oil (eranda taila)": "एरंड तैल (अरंडी का तेल)",
    "Chandanadi taila (head application)": "चंदनादि तैल (सिर पर लगाने के लिए)",
    "Chaturbeeja churna": "चतुर्बीज चूर्ण",
    "Chitraka haritaki avaleha": "चित्रक हरीतकी अवलेह",
    "Chopchini churna": "चोपचीनी चूर्ण",
    "Cow's ghee nasal drops (Gau ghrita nasya)": "गौ घृत नस्य (नाक में गाय का घी)",
    "Dadima phala twak churna (pomegranate rind)": "दाडिम फल त्वक् चूर्ण (अनार का छिलका)",
    "Dadimashtaka churna": "दाडिमाष्टक चूर्ण",
    "Darvighana with Gairika": "दार्वीघन के साथ गैरिक",
    "Dashamoola kashaya": "दशमूल कषाय",
    "Dashamoola kwatha": "दशमूल क्वाथ",
    "Dashamoola taila (scalp massage)": "दशमूल तैल (सिर की मालिश)",
    "Dashamoolarishta": "दशमूलारिष्ट",
    "Dashana samskara churna": "दशन संस्कार चूर्ण",
    "Dashanga lepa": "दशांग लेप",
    "Devadarvyadi kwatha": "देवदार्व्यादि क्वाथ",
    "Dhanvantara taila": "धन्वंतर तैल",
    "Dhanwantaram taila (101 avarti, oral drops)": "धन्वंतरम् तैल (101 आवर्ती, मुंह से बूंदें)",
    "Dhanwantharam kwatha": "धन्वंतरम् क्वाथ",
    "Draksha (dried black raisins)": "द्राक्षा (काली किशमिश / मुनक्का)",
    "Drakshadi kwatha": "द्राक्षादि क्वाथ",
    "Drakshadi leha": "द्राक्षादि लेह",
    "Draksharishta": "द्राक्षारिष्ट",
    "Drakshavaleha": "द्राक्षावलेह",
    "Eranda bhrishta haritaki with shunthi": "एरंड भृष्ट हरीतकी के साथ शुंठी",
    "Erandamoola kwatha": "एरंडमूल क्वाथ",
    "Erandamula kwatha": "एरंडमूल क्वाथ",
    "Gojihvadi kwatha": "गोजिह्वादि क्वाथ",
    "Guggulu tiktaka ghrita": "गुग्गुलु तिक्तक घृत",
    "Guggulu tiktakam kwatha": "गुग्गुलु तिक्तकम् क्वाथ",
    "Haridra khanda": "हरिद्रा खंड",
    "Haritaki churna": "हरीतकी चूर्ण",
    "Hingvadi churna": "हिंग्वादि चूर्ण",
    "Hingvadi gutika": "हिंग्वादि गुटिका",
    "Hingvashtaka churna": "हिंग्वाष्टक चूर्ण",
    "Hingwashtaka churna": "हिंग्वाष्टक चूर्ण",
    "Honey gargle (kshaudra)": "शहद से कुल्ला (क्षौद्र)",
    "Irimedadi taila": "इरिमेदादि तैल",
    "Jatipatra (jasmine leaf) paste": "जातीपत्र (चमेली की पत्ती) का लेप",
    "Jatiphala churna (nutmeg)": "जातीफल चूर्ण (जायफल)",
    "Jatyadi taila": "जात्यादि तैल",
    "Kaishora guggulu": "कैशोर गुग्गुलु",
    "Kalaka churna": "कालक चूर्ण",
    "Kantakari avaleha": "कंटकारी अवलेह",
    "Kantakari ghrita": "कंटकारी घृत",
    "Kantakaryadi kwatha": "कंटकार्यादि क्वाथ",
    "Karpasasthyadi taila": "कार्पासास्थ्यादि तैल",
    "Khadiradi gutika": "खदिरादि गुटिका",
    "Khadiradi vati": "खदिरादि वटी",
    "Kottamchukkadi taila": "कोट्टमचुक्कादि तैल",
    "Ksheerabala taila": "क्षीरबला तैल",
    "Ksheerabala taila (head application)": "क्षीरबला तैल (सिर पर लगाने के लिए)",
    "Kshiri vriksha kashaya": "क्षीरी वृक्ष कषाय",
    "Kutaja avaleha": "कुटज अवलेह",
    "Kutaja churna": "कुटज चूर्ण",
    "Kutaja ghana vati": "कुटज घन वटी",
    "Kutajarishta": "कुटजारिष्ट",
    "Lavangadi vati": "लवंगादि वटी",
    "Mahanarayana taila": "महानारायण तैल",
    "Maharasnadi kwatha": "महारास्नादि क्वाथ",
    "Mamsyadi kwatha": "मांस्यादि क्वाथ",
    "Masha taila": "माष तैल",
    "Murivenna": "मुरिवेण्णा",
    "Murivenna / Dhanwantharam taila / Nirgundyadi taila / Bala taila": "मुरिवेण्णा / धन्वंतरम् तैल / निर्गुंड्यादि तैल / बला तैल",
    "Musta churna": "मुस्ता चूर्ण",
    "Mustakaranjadi kashaya": "मुस्ताकरंजादि कषाय",
    "Narikela lavana": "नारिकेल लवण",
    "Nimbadi churna": "निंबादि चूर्ण",
    "Nirgundi taila": "निर्गुंडी तैल",
    "Panchapallava kwatha gargle": "पंचपल्लव क्वाथ से कुल्ला",
    "Panchatikta kwatha gargle": "पंचतिक्त क्वाथ से कुल्ला",
    "Panchavalkala kwatha": "पंचवल्कल क्वाथ",
    "Panchavalkala kwatha gargle": "पंचवल्कल क्वाथ से कुल्ला",
    "Panchavalkala kwatha sitz bath (avagaha)": "पंचवल्कल क्वाथ से बैठकर स्नान (अवगाह)",
    "Parinata keryadi taila": "परिणत केर्यादि तैल",
    "Pathyadi kwatha": "पथ्यादि क्वाथ",
    "Patoladi kwatha": "पटोलादि क्वाथ",
    "Phalatrikadi kwatha": "फलत्रिकादि क्वाथ",
    "Pippalimula churna": "पिप्पलीमूल चूर्ण",
    "Pippalyadi ghrita": "पिप्पल्यादि घृत",
    "Pitaka churna": "पीतक चूर्ण",
    "Prabhanjana vimardana taila": "प्रभंजन विमर्दन तैल",
    "Prasaranyadi kashaya": "प्रसारण्यादि कषाय",
    "Prasarini taila": "प्रसारिणी तैल",
    "Rasna churna": "रास्ना चूर्ण",
    "Rasnasaptakam kashaya": "रास्नासप्तकम् कषाय",
    "Sahachara taila": "सहचर तैल",
    "Samasharkara churna": "समशर्करा चूर्ण",
    "Samshamani vati (guduchi)": "संशमनी वटी (गुडूची / गिलोय)",
    "Saptasaram kashaya": "सप्तसारम् कषाय",
    "Saraswata churna": "सारस्वत चूर्ण",
    "Shadbindu taila": "षड्बिंदु तैल",
    "Shati churna": "शटी चूर्ण",
    "Shivakshara pachana churna": "शिवाक्षार पाचन चूर्ण",
    "Shrungyadi churna": "शृंग्यादि चूर्ण",
    "Shunthi churna": "शुंठी चूर्ण (सोंठ)",
    "Simhanada guggulu": "सिंहनाद गुग्गुलु",
    "Sitopaladi churna": "सितोपलादि चूर्ण",
    "Soubhagya shunthi paka": "सौभाग्य शुंठी पाक",
    "Swadishta virechana churna": "स्वादिष्ट विरेचन चूर्ण",
    "Tagara churna": "तगर चूर्ण",
    "Talishadi churna": "तालीसादि चूर्ण",
    "Trikatu churna": "त्रिकटु चूर्ण",
    "Trikatu with Vasa (with honey)": "त्रिकटु के साथ वासा (शहद के साथ)",
    "Triphala churna": "त्रिफला चूर्ण",
    "Triphala guggulu": "त्रिफला गुग्गुलु",
    "Triphala kwatha gargle": "त्रिफला क्वाथ से कुल्ला",
    "Triphala kwatha sitz bath (avagaha)": "त्रिफला क्वाथ से बैठकर स्नान (अवगाह)",
    "Vasa swarasa / Vasa churna": "वासा स्वरस / वासा चूर्ण",
    "Vasavaleha": "वासावलेह",
    "Vidanga avaleha": "विडंग अवलेह",
    "Vidangadi churna": "विडंगादि चूर्ण",
    "Vidangarishta": "विडंगारिष्ट",
    "Vidaryadi kwatha": "विदार्यादि क्वाथ",
    "Vyaghri haritaki avaleha": "व्याघ्री हरीतकी अवलेह",
    "Vyoshadi vati": "व्योषादि वटी",
    "Yashtimadhu churna": "यष्टिमधु चूर्ण (मुलेठी)",
    "Yashtimadhu churna with Gairika, in honey and ghee": "यष्टिमधु चूर्ण के साथ गैरिक, शहद और घी में",
    "Yogaraja guggulu": "योगराज गुग्गुलु",
}

# Herb records whose research entry had no Devanagari name.
HERBS_HI = {
    "haritaki": "हरड़ / हरीतकी", "bibhitaki": "बहेड़ा", "kutki": "कुटकी", "kalmegh": "कालमेघ",
    "moringa": "सहजन", "ajwain": "अजवाइन", "black_pepper": "काली मिर्च", "pippali": "पिप्पली / पीपल",
    "saffron": "केसर", "vacha": "वच", "jatamansi": "जटामांसी", "sarpagandha": "सर्पगंधा",
    "kapikacchu": "कौंच / कपिकच्छू", "bhringraj": "भृंगराज", "manjistha": "मंजीठ", "ashoka": "अशोक",
    "lodhra": "लोध्र", "daruharidra": "दारुहल्दी", "vijaysar": "विजयसार", "chirata": "चिरायता",
    "shallaki": "शल्लकी / सलई गुग्गुल", "vasaka": "अडूसा / वासा", "bakuchi": "बाकुची / बावची",
    "bhallataka": "भिलावा", "kuchla": "कुचला", "vatsanabh": "बच्छनाग / वत्सनाभ", "dhatura": "धतूरा",
    "hing": "हींग", "saunf": "सौंफ", "elaichi": "इलायची", "laung": "लौंग", "jaiphal": "जायफल",
    "nagarmotha": "नागरमोथा", "bala": "बला / खरेंटी", "chitrak": "चित्रक", "nirgundi": "निर्गुंडी",
    "rasna": "रास्ना", "devdaru": "देवदार", "jyotishmati": "मालकांगनी / ज्योतिष्मती", "vidari_kand": "विदारीकंद",
    "kantakari": "कटेरी / कंटकारी", "varun": "वरुण", "pashanbhed": "पाषाणभेद", "khadira": "कत्था / खदिर",
    "kanchnar": "कचनार", "bael": "बेल", "kokum": "कोकम", "garcinia_cambogia": "गार्सिनिया कैम्बोजिया",
    "green_tea_extract": "ग्रीन टी अर्क", "ginseng": "जिनसेंग", "st_johns_wort": "सेंट जॉन्स वॉर्ट",
    "sea_buckthorn": "सी बकथॉर्न / छरमा",
}
