"""Hand-curated rules used by build_medicines.py.

Everything here is either (a) copied from a cited public source (FDA tables, NLEM, Drugs Rules)
or (b) a pharmacology fact a pharmacist would recognise (salt names, INN/USAN synonyms, class
membership). Entries whose fit to a spec key is a judgement call carry a note that ends up in
medicines_notes.md. Do not add a molecule→class rule you cannot back with a label, FDA table,
or standard pharmacology reference.
"""

# --------------------------------------------------------------------------------------------
# Name normalisation
# --------------------------------------------------------------------------------------------

# Counter-ions, esters and hydrates stripped from ingredient names ("metformin hydrochloride"
# -> "metformin"). Only stripped when something pharmacologically meaningful remains.
SALT_TOKENS = {
    "hydrochloride", "dihydrochloride", "monohydrochloride", "hcl", "hydrobromide", "hydroiodide",
    "sodium", "disodium", "potassium", "dipotassium", "calcium", "magnesium", "sulfate", "sulphate",
    "bisulfate", "succinate", "maleate", "hemifumarate", "fumarate", "tartrate",
    "bitartrate", "besylate", "besilate", "mesylate", "mesilate", "dimesylate", "tosylate",
    "citrate", "acetate", "diacetate", "phosphate", "monohydrate", "dihydrate", "trihydrate",
    "tetrahydrate", "pentahydrate", "hexahydrate", "heptahydrate", "hemihydrate", "sesquihydrate",
    "hydrate", "anhydrous", "hyclate", "bromide", "chloride", "nitrate", "lactate", "gluconate",
    "oxalate", "medoxomil", "propionate", "dipropionate", "valerate", "acetonide", "furoate",
    "pivalate", "axetil", "etexilate", "mofetil", "disoproxil", "alafenamide", "napsylate",
    "pamoate", "embonate", "decanoate", "enanthate", "cypionate", "palmitate", "stearate",
    "estolate", "ethylsuccinate", "lauroxil", "xinafoate", "iodide", "tromethamine", "trometamol",
    "meglumine", "dimeglumine", "lysine", "olamine", "diethylamine", "dithylamine", "epolamine",
    "erbumine", "arginine", "saccharate", "aspartate", "camsylate",
    "edisylate", "isethionate", "lactobionate", "mandelate", "methylbromide", "methylsulfate",
    "nitrite", "orotate", "polistirex", "resinate", "stearoyl", "teoclate", "trifenatate",
    "hippurate", "mucate", "glycinate", "bisglycinate", "monosodium", "trisodium", "dimaleate",
    "dicitrate", "monophosphate", "diphosphate", "hydrogensulfate", "sesquifumarate",
    "malate", "hemitartrate", "hemisulfate", "sulfosalicylate", "tannate", "ascorbate",
    "probutate", "buciclate", "butyrate", "aceponate", "hexacetonide", "tebutate",
    "carbonate", "bicarbonate", "oxide", "hydroxide", "monobasic", "dibasic",
    "(synthetic)", "(natural)", "form", "unspecified", "ip", "bp", "usp", "kamedoxomil",
    "s-malate", "caproate", "ethanolate", "esylate", "monoethanolate", "hyclate,", "dimethyl",
}

# Words that are a molecule only together with their counter-ion: "potassium chloride",
# "lithium carbonate", "ferrous sulfate". If stripping leaves only these, keep the full name.
ION_BASES = {
    "sodium", "potassium", "calcium", "magnesium", "lithium", "zinc", "ferrous", "ferric", "iron",
    "aluminum", "aluminium", "ammonium", "silver", "copper", "cupric", "manganese", "chromium",
    "chromic", "selenium", "strontium", "barium", "bismuth", "cobalt", "titanium", "hydrogen",
    "stannous", "gold", "gallium", "lanthanum", "cesium", "thallous", "rubidium", "sodium,",
    "acid", "", "mercuric", "boric", "nitric", "sulfuric", "carbon", "nitrous", "aminolevulinic",
}

# INN / BAN / Indian Pharmacopoeia names -> the US (USAN) name openFDA uses. Indian labels print
# the IP/INN name (Drugs Rules r.96), so the scanner will see the left-hand side.
SYNONYMS = {
    "paracetamol": "acetaminophen",
    "salbutamol": "albuterol",
    "levosalbutamol": "levalbuterol",
    "adrenaline": "epinephrine",
    "noradrenaline": "norepinephrine",
    "lignocaine": "lidocaine",
    "glibenclamide": "glyburide",
    "frusemide": "furosemide",
    "torasemide": "torsemide",
    "rifampicin": "rifampin",
    "phenobarbitone": "phenobarbital",
    "thiopentone": "thiopental",
    "pethidine": "meperidine",
    "acetylsalicylic acid": "aspirin",
    "glyceryl trinitrate": "nitroglycerin",
    "isoprenaline": "isoproterenol",
    "ciclosporin": "cyclosporine",
    "cyclosporin": "cyclosporine",
    "cefalexin": "cephalexin",
    "amoxycillin": "amoxicillin",
    "dicycloverine": "dicyclomine",
    "mesalazine": "mesalamine",
    "mesalaine": "mesalamine",
    "5-aminosalicylic acid": "mesalamine",
    "thyroxine": "levothyroxine",
    "l-thyroxine": "levothyroxine",
    "colecalciferol": "cholecalciferol",
    "phytomenadione": "phytonadione",
    "vitamin k1": "phytonadione",
    "sulphamethoxazole": "sulfamethoxazole",
    "sulphasalazine": "sulfasalazine",
    "sulphadiazine": "sulfadiazine",
    "silver sulphadiazine": "silver sulfadiazine",
    "sulphadoxine": "sulfadoxine",
    "dothiepin": "dosulepin",
    "chlorphenamine": "chlorpheniramine",
    "benzylpenicillin": "penicillin g",
    "benzathine benzylpenicillin": "penicillin g benzathine",
    "procaine benzylpenicillin": "penicillin g procaine",
    "phenoxymethyl penicillin": "penicillin v",
    "phenoxymethylpenicillin": "penicillin v",
    "cytosine arabinoside": "cytarabine",
    "actinomycin d": "dactinomycin",
    "5-fluorouracil": "fluorouracil",
    "6-mercaptopurine": "mercaptopurine",
    "all-trans retinoic acid": "tretinoin",
    "l-asparaginase": "asparaginase",
    "desferrioxamine": "deferoxamine",
    "d- penicillamine": "penicillamine",
    "d-penicillamine": "penicillamine",
    "hydroxocobalamine": "hydroxocobalamin",
    "calcium folinate": "leucovorin",
    "folinic acid": "leucovorin",
    "methylrosanilinium chloride": "gentian violet",
    "methylthioninium chloride": "methylene blue",
    "n-acetylcysteine": "acetylcysteine",
    "para- aminosalicylic acid": "aminosalicylic acid",
    "para-aminosalicylic acid": "aminosalicylic acid",
    "ispaghula": "psyllium",
    "ispaghula husk": "psyllium",
    "sodium valproate": "valproic acid",
    "valproate": "valproic acid",
    "divalproex": "valproic acid",
    "suxamethonium": "succinylcholine",
    "oestradiol": "estradiol",
    "ethinyloestradiol": "ethinyl estradiol",
    "ethinylestradiol": "ethinyl estradiol",
    "norethisterone": "norethindrone",
    "dexamphetamine": "dextroamphetamine",
    "clomifene": "clomiphene",
    "beclometasone": "beclomethasone",
    "aciclovir": "acyclovir",
    "valaciclovir": "valacyclovir",
    "benzhexol": "trihexyphenidyl",
    "orciprenaline": "metaproterenol",
    "ergometrine": "ergonovine",
    "methylergometrine": "methylergonovine",
    "chlortalidone": "chlorthalidone",
    "clavulanic acid": "clavulanate",
    "potassium clavulanate": "clavulanate",
    "diluted potassium clavulanate": "clavulanate",
    "tenofovir disproxil fumarate": "tenofovir",
    "tenofovir disoproxil": "tenofovir",
    "tenofovir alafenamide fumarate": "tenofovir",
    "dabigatran etexilate": "dabigatran",
    "mycophenolate": "mycophenolic acid",
    "ursodeoxycholic acid": "ursodiol",
    "amphotericin b (conventional)": "amphotericin b",
    "lipid amphotericin b": "amphotericin b",
    "liposomal amphotericin b": "amphotericin b",
    "betamethasone (valerate)": "betamethasone",
    "insulin (soluble)": "insulin human",
    "insulin soluble": "insulin human",
    "insulin intermediate acting (nph)": "insulin isophane human",
    "isophane insulin": "insulin isophane human",
    "human insulin": "insulin human",
    "erythropoietin": "epoetin alfa",
    "irinotecan hci trihydrate": "irinotecan",
    "lithium": "lithium carbonate",
    "ascorbic acid (vitamin c)": "ascorbic acid",
    "vitamin c": "ascorbic acid",
    "vitamin a": "vitamin a",
    "s(-) amlodipine": "levamlodipine",
    "s-amlodipine": "levamlodipine",
    "s (-) amlodipine": "levamlodipine",
    "escitalopram oxalate": "escitalopram",
    "esomeprazole magnesium": "esomeprazole",
    "levocetirizine dihydrochloride": "levocetirizine",
    "glycopyrronium": "glycopyrrolate",
    "hyoscine hydrobromide": "scopolamine",
    "co-trimoxazole": "sulfamethoxazole|trimethoprim",
    "cotrimoxazole": "sulfamethoxazole|trimethoprim",
    "oral rehydration salts": "oral rehydration salts",
    "rehydration salts": "oral rehydration salts",
    "sulfadoxine pyrimethamine": "sulfadoxine|pyrimethamine",
    "insulin premix injection 30:70": "insulin human|insulin isophane human",
    "insulin": "insulin human",
    "soluble insulin": "insulin human",
    "isophane": "insulin isophane human",
    "paraffin": "mineral oil",
    "light paraffin": "mineral oil",
    "milk magnesia": "magnesium hydroxide",
    "milk of magnesia": "magnesium hydroxide",
    "dried aluminum hydroxide": "aluminum hydroxide",
    "vitamin k": "phytonadione",
    "calcipotriol": "calcipotriene",
    "dithranol": "anthralin",
    "nicotinamide": "niacinamide",
    "picosulfate": "sodium picosulfate",
    "sodium picosulfate": "sodium picosulfate",
    "ringer lactate": "ringer lactate",
    "eicosapentaenoic acid": "icosapent ethyl",
    "flupenthixol": "flupentixol",
    "zinc sulphate": "zinc sulfate",
    "magnesium sulphate": "magnesium sulfate",
    "barium sulphate": "barium sulfate",
    "protamine sulphate": "protamine sulfate",
    "sodium thiosulphate": "sodium thiosulfate",
    "ferrous sulphate": "ferrous sulfate",
    "ondansetron hydrochloride": "ondansetron",
    "cyanocobalamine": "cyanocobalamin",
    "methylcobalamine": "methylcobalamin",
    "mecobalamin": "methylcobalamin",
    "sennoside": "sennosides",
    "senna": "sennosides",
    "centchroman": "ormeloxifene",
    "trypsin-chymotrypsin": "trypsin|chymotrypsin",
    "trypsin chymotrypsin": "trypsin|chymotrypsin",
    "pralidoxime chloride (2-pam)": "pralidoxime",
    "phytomenadione(vitamin k1)": "phytonadione",
    "dl-methionine": "methionine",
    "liquid paraffin": "mineral oil",
    "light liquid paraffin": "mineral oil",
    "hydroxypropyl methylcellulose": "hypromellose",
    "carboxymethyl cellulose": "carboxymethylcellulose",
    "carboxymethylcellulose sodium": "carboxymethylcellulose",
    "carmellose": "carboxymethylcellulose",
    "ethyl alcohol (denatured)": "alcohol",
    "povidone iodine": "povidone-iodine",
    "lactic acid bacillus": "lactobacillus",
    "glucose": "dextrose",
    "levonorgestrel releasing iud": "levonorgestrel",
    "tranexamic": "tranexamic acid",
    "deriphylline": "etofylline|theophylline",
    "theophylline anhydrous": "theophylline",
    "doxophylline": "doxofylline",
    "cyclosporin a": "cyclosporine",
    "cyclosporine a": "cyclosporine",
    "metformin hydrochloride": "metformin",
    "insulin regular": "insulin human",
    "dydrogestrone": "dydrogesterone",
    "luliconazole": "luliconazole",
    "acenocoumarol": "acenocoumarol",
    "nicoumalone": "acenocoumarol",
    "isosorbide-5-mononitrate": "isosorbide mononitrate",
    "isosorbide 5-mononitrate": "isosorbide mononitrate",
    "glimepride": "glimepiride",
    "rabeprazole sodium": "rabeprazole",
    "pantoprazole sodium": "pantoprazole",
    "amlodipine besilate": "amlodipine",
    "atorvastatin calcium": "atorvastatin",
    "fluphenazine decanoate": "fluphenazine",
    "haloperidol decanoate": "haloperidol",
    "medroxyprogesterone acetate": "medroxyprogesterone",
    "leuprolide acetate": "leuprolide",
    "clomiphene citrate": "clomiphene",
    "bendamustine hydrochloride": "bendamustine",
    "tenofovir alafenamide": "tenofovir",
    "nicotine replacement therapy (nrt)": "nicotine",
    "vitamin d3": "cholecalciferol",
    "vitamin b12": "cyanocobalamin",
    "vitamin b6": "pyridoxine",
    "vitamin b1": "thiamine",
    "vitamin b2": "riboflavin",
    "vitamin e": "vitamin e",
    "tocopheryl acetate": "vitamin e",
    "dl-alpha tocopheryl acetate": "vitamin e",
    "levo-carnitine": "levocarnitine",
    "l-carnitine": "levocarnitine",
    "amphotericin-b": "amphotericin b",
    "itraconazole capsules": "itraconazole",
    "dexchlorpheniramine maleate": "dexchlorpheniramine",
    "omega 3 fatty acids": "omega-3-acid ethyl esters",
    "hydroxy chloroquine": "hydroxychloroquine",
    "hydroxychloroquine sulphate": "hydroxychloroquine",
    "pyrantel pamoate": "pyrantel",
    "alpha lipoic acid": "thioctic acid",
    "lipoic acid": "thioctic acid",
}

# Misspellings found in the Jan Aushadhi product list (and common OCR/print variants).
# Kept apart from SYNONYMS so medicine_aliases.csv can label them "spelling_variant".
SPELLING_VARIANTS = {
    "glimipride": "glimepiride",
    "flecanide": "flecainide",
    "cetrizine": "cetirizine",
    "levocetrizine": "levocetirizine",
    "nimesulid": "nimesulide",
    "isosorbidemononitrate": "isosorbide mononitrate",
    "trihexiphenidyl": "trihexyphenidyl",
    "flurouracil": "fluorouracil",
    "dosulepine": "dosulepin",
    "nortryptyline": "nortriptyline",
    "ofloxaxin": "ofloxacin",
    "tazobactum": "tazobactam",
    "duloxetin": "duloxetine",
    "thiocholchicoside": "thiocolchicoside",
    "carboxymethlycellulose": "carboxymethylcellulose",
    "megaldrate": "magaldrate",
    "di-cloxacillin": "dicloxacillin",
    "guaiphenesin": "guaifenesin",
    "levo-thyroxine": "levothyroxine",
    "etophyllin": "etofylline",
    "etophylline": "etofylline",
    "etofyllin": "etofylline",
    "alpha lipolic acid": "thioctic acid",
    "hydroxypropylmethylcellulose": "hypromellose",
    "trimetazidine hydrochloride": "trimetazidine",
    "human chorionic gonadotrophin": "chorionic gonadotropin",
    "human chorionic gonadotropin": "chorionic gonadotropin",
    "l ornithine l-aspartate": "l-ornithine l-aspartate",
    "l ornithin l aspartate": "l-ornithine l-aspartate",
    "co-enzyme q": "ubidecarenone",
    "coenzyme q": "ubidecarenone",
    "coenzyme q10": "ubidecarenone",
    "co-enzyme q10": "ubidecarenone",
    "s-metoprolol": "s-metoprolol",
    "gama benzene hexachloride": "lindane",
    "gamma benzene hexachloride": "lindane",
}

# Molecules found on the NLEM / Jan Aushadhi lists that openFDA does not cover (mostly not
# US-marketed). Listed so the Jan Aushadhi matcher recognises them; classes, where any, are in
# OVERRIDES. Each name was read off the PMBI product list or NLEM 2022.
INDIA_MOLECULES = {
    "levosulpiride", "thiocolchicoside", "serratiopeptidase", "lycopene", "pancreatin",
    "diacerein", "citicoline", "drotaverine", "piracetam", "cinnarizine", "ubidecarenone",
    "fungal diastase", "racecadotril", "disodium hydrogen citrate", "betahistine", "oxetacaine",
    "nandrolone", "itopride", "ebastine", "ambroxol", "l-arginine", "melatonin", "topiroxostat",
    "feracrylum", "s-metoprolol", "mosapride", "tricholine citrate", "etofylline", "l-lysine",
    "etamsylate", "cetrimide", "chondroitin", "trimetazidine", "cinitapride", "bromelain",
    "rutoside", "bilastine", "silymarin", "l-ornithine l-aspartate", "saccharomyces boulardii",
    "inositol", "myo-inositol", "procyclidine", "efonidipine", "levocloperastine", "rupatadine",
    "furazolidone", "arteether", "bacillus clausii", "alfacalcidol", "bromhexine",
    "methylsulfonylmethane", "nalidixic acid", "dehydroepiandrosterone", "isoxsuprine", "noscapine",
    "allylestrenol", "mebeverine", "teicoplanin", "valethamate", "acotiamide", "amorolfine",
    "camylofin", "cerebroprotein hydrolysate", "melitracen", "l-methylfolate", "lactitol",
    "levodropropizine", "metadoxine", "oxaceprol", "dithranol", "epalrestat", "tolperisone",
    "cyproterone", "benfotiamine", "bifonazole", "eberconazole", "luliconazole", "d-mannose",
    "eicosapentaenoic acid", "pepsin", "papain", "alpha amylase", "chlorbutol", "paradichlorobenzene",
    "chlorothymol", "chlorocresol", "benzyl nicotinate", "astaxanthin", "zeaxanthin",
    "methylcobalamin", "ferrous ascorbate", "aceclofenac", "nimesulide", "etoricoxib", "lornoxicam",
    "teneligliptin", "vildagliptin", "voglibose", "gliclazide", "remogliflozin", "imeglimin",
    "saroglitazar", "evogliptin", "cilnidipine", "azelnidipine", "benidipine", "nicorandil",
    "acenocoumarol", "ilaprazole", "domperidone", "ornidazole", "satranidazole", "faropenem",
    "roxithromycin", "prulifloxacin", "dydrogesterone", "ormeloxifene", "tibolone", "etizolam",
    "dosulepin", "agomelatine", "amisulpride", "flupentixol", "zuclopenthixol", "doxofylline",
    "acebrophylline", "deflazacort", "carbimazole", "nitrazepam", "zopiclone", "moxonidine",
    "lercanidipine", "dapoxetine", "trypsin", "chymotrypsin", "sodium picosulfate", "mecobalamin",
    "calcipotriol", "dexketoprofen", "aceclofenac", "zaltoprofen", "flupirtine", "lobeglitazone",
    "iron polymaltose", "ferric hydroxide polymaltose", "sodium feredetate", "ferrous bisglycinate",
    "magaldrate", "magnesium trisilicate", "dicyclomine", "ivabradine", "ranolazine", "linagliptin",
}

# --------------------------------------------------------------------------------------------
# FDA Established Pharmacologic Class (EPC) -> spec drug_class keys
# Exact EPC strings as openFDA prints them, minus the " [EPC]" suffix.
# --------------------------------------------------------------------------------------------
EPC_MAP = {
    "Vitamin K Antagonist": ["anticoagulant_vka"],
    # Oral agents; parenteral members (fondaparinux, argatroban, bivalirudin...) are moved to
    # anticoagulant_heparin by OVERRIDES.
    "Factor Xa Inhibitor": ["anticoagulant_doac"],
    "Direct Thrombin Inhibitor": ["anticoagulant_doac"],
    "Low Molecular Weight Heparin": ["anticoagulant_heparin"],
    "Unfractionated Heparin": ["anticoagulant_heparin"],
    "Platelet Aggregation Inhibitor": ["antiplatelet"],
    "P2Y12 Platelet Inhibitor": ["antiplatelet"],
    # Spec lists "NSAIDs at high dose" under nephrotoxic, so the class carries both keys.
    "Nonsteroidal Anti-inflammatory Drug": ["nsaid", "nephrotoxic"],
    "Insulin": ["antidiabetic_insulin"],
    "Insulin Analog": ["antidiabetic_insulin"],
    "Sulfonylurea": ["antidiabetic_sulfonylurea"],
    "Biguanide": ["antidiabetic_other"],
    "Dipeptidyl Peptidase 4 Inhibitor": ["antidiabetic_other"],
    "Sodium-Glucose Cotransporter 2 Inhibitor": ["antidiabetic_other"],
    "Thiazolidinedione": ["antidiabetic_other"],
    "GLP-1 Receptor Agonist": ["antidiabetic_other"],
    "Glinide": ["antidiabetic_other"],
    "alpha-Glucosidase Inhibitor": ["antidiabetic_other"],
    "Amylin Analog": ["antidiabetic_other"],
    "Glucose-dependent Insulinotropic Polypeptide Receptor Agonist": ["antidiabetic_other"],
    # Spec: potassium_sparing "(+ ACEi/ARB hyperkalaemia risk)" -> ACEi/ARB/renin inhibitors
    # carry potassium_sparing as well as antihypertensive.
    "Angiotensin Converting Enzyme Inhibitor": ["antihypertensive", "potassium_sparing"],
    "Angiotensin 2 Receptor Blocker": ["antihypertensive", "potassium_sparing"],
    "Renin Inhibitor": ["antihypertensive", "potassium_sparing"],
    "Calcium Channel Blocker": ["antihypertensive"],
    "Dihydropyridine Calcium Channel Blocker": ["antihypertensive"],
    "beta-Adrenergic Blocker": ["antihypertensive"],
    "alpha-Adrenergic Blocker": ["antihypertensive"],
    "Central alpha-2 Adrenergic Agonist": ["antihypertensive"],
    "Arteriolar Vasodilator": ["antihypertensive"],
    "Loop Diuretic": ["diuretic_loop_thiazide"],
    "Thiazide Diuretic": ["diuretic_loop_thiazide", "antihypertensive"],
    "Thiazide-like Diuretic": ["diuretic_loop_thiazide", "antihypertensive"],
    "Potassium-sparing Diuretic": ["potassium_sparing"],
    "Aldosterone Antagonist": ["potassium_sparing"],
    "Nonsteroidal Mineralocorticoid-Receptor Antagonist": ["potassium_sparing"],
    "Cardiac Glycoside": ["cardiac_glycoside"],
    "Antiarrhythmic": ["antiarrhythmic"],
    "Nitrate Vasodilator": ["nitrate_pde5"],
    "Phosphodiesterase 5 Inhibitor": ["nitrate_pde5"],
    "HMG-CoA Reductase Inhibitor": ["statin"],
    "l-Thyroxine": ["thyroid_hormone"],
    "l-Triiodothyronine": ["thyroid_hormone"],
    "Thyroid Hormone Synthesis Inhibitor": ["antithyroid"],
    "Calcineurin Inhibitor Immunosuppressant": ["immunosuppressant"],
    "mTOR Inhibitor Immunosuppressant": ["immunosuppressant"],
    "Antimetabolite Immunosuppressant": ["immunosuppressant"],
    "Selective T Cell Costimulation Blocker": ["immunosuppressant"],
    "Selective T Cell Costimulation Modulator": ["immunosuppressant"],
    "Interleukin-2 Receptor Blocking Antibody": ["immunosuppressant"],
    "Janus Kinase Inhibitor": ["immunosuppressant"],
    "Tumor Necrosis Factor Blocker": ["immunosuppressant"],
    "Sphingosine 1-phosphate Receptor Modulator": ["immunosuppressant"],
    "Pyrimidine Synthesis Inhibitor": ["immunosuppressant"],
    "Interleukin-6 Receptor Antagonist": ["immunosuppressant"],
    "Corticosteroid": ["corticosteroid"],
    "Serotonin Reuptake Inhibitor": ["antidepressant_ssri_snri"],
    "Serotonin and Norepinephrine Reuptake Inhibitor": ["antidepressant_ssri_snri"],
    "Monoamine Oxidase Inhibitor": ["antidepressant_maoi"],
    # Judgement call: MAO-B inhibitors share the MAOI serotonergic/tyramine warnings.
    "Monoamine Oxidase Type B Inhibitor": ["antidepressant_maoi"],
    "Tricyclic Antidepressant": ["antidepressant_tca"],
    "Benzodiazepine": ["sedative_hypnotic"],
    "Barbiturate": ["sedative_hypnotic"],
    "Orexin Receptor Antagonist": ["sedative_hypnotic"],
    "Central Nervous System Depressant": ["sedative_hypnotic"],
    "gamma-Aminobutyric Acid A Receptor Agonist": ["sedative_hypnotic"],
    "Anti-epileptic Agent": ["antiepileptic"],
    "Noncompetitive AMPA Glutamate Receptor Antagonist": ["antiepileptic"],
    "Atypical Antipsychotic": ["antipsychotic"],
    "Typical Antipsychotic": ["antipsychotic"],
    "Opioid Agonist": ["opioid"],
    "Partial Opioid Agonist": ["opioid"],
    "Opioid Agonist/Antagonist": ["opioid"],
    "Partial Opioid Agonist/Antagonist": ["opioid"],
    "mu-Opioid Receptor Agonist": ["opioid"],
    # Anticancer: cytotoxics, targeted and hormonal oncology classes.
    "Kinase Inhibitor": ["anticancer"],
    "Alkylating Drug": ["anticancer"],
    "Microtubule Inhibitor": ["anticancer"],
    "Platinum-based Drug": ["anticancer"],
    "Anthracycline Topoisomerase Inhibitor": ["anticancer"],
    "Topoisomerase Inhibitor": ["anticancer"],
    "Nucleoside Metabolic Inhibitor": ["anticancer"],
    "Folate Analog Metabolic Inhibitor": ["anticancer"],
    "Aromatase Inhibitor": ["anticancer"],
    "Estrogen Receptor Antagonist": ["anticancer"],
    "Androgen Receptor Inhibitor": ["anticancer"],
    "Cytochrome P450 17A1 Inhibitor": ["anticancer"],
    "Proteasome Inhibitor": ["anticancer"],
    "Poly(ADP-Ribose) Polymerase Inhibitor": ["anticancer"],
    "Histone Deacetylase Inhibitor": ["anticancer"],
    "Hedgehog Pathway Inhibitor": ["anticancer"],
    "BCL-2 Inhibitor": ["anticancer"],
    "Vinca Alkaloid": ["anticancer"],
    "Thalidomide Analog": ["anticancer"],
    "Programmed Death Receptor-1 Blocking Antibody": ["anticancer"],
    "Programmed Death Ligand-1 Blocker": ["anticancer"],
    "CTLA-4-directed Blocking Antibody": ["anticancer"],
    "HER2/neu Receptor Antagonist": ["anticancer"],
    "Bispecific HER2-directed Antibody": ["anticancer"],
    "CD38-directed Cytolytic Antibody": ["anticancer"],
    "Isocitrate Dehydrogenase 1 Inhibitor": ["anticancer"],
    "Isocitrate Dehydrogenase 2 Inhibitor": ["anticancer"],
    "Menin Inhibitor": ["anticancer"],
    "Nuclear Export Inhibitor": ["anticancer"],
    "Actinomycin": ["anticancer"],
    "Bispecific CD20-directed CD3 T Cell Engager": ["anticancer"],
    "Epidermal Growth Factor Receptor Antagonist": ["anticancer"],
    "Oligonucleotide Telomerase Inhibitor": ["anticancer"],
    "Radioligand Therapeutic Agent": ["anticancer"],
    "Antimetabolite": ["anticancer"],
    "Purine Antimetabolite": ["anticancer"],
    "Methylating Agent": ["anticancer"],
    "Tubulin Inhibiting Agent": ["anticancer"],
    "CD19-directed Cytolytic Antibody": ["anticancer"],
    "CD22-directed Immunoconjugate": ["anticancer"],
    "CD30-directed Immunoconjugate": ["anticancer"],
    "CD33-directed Immunoconjugate": ["anticancer"],
    "SLAMF7-directed Immunostimulatory Antibody": ["anticancer"],
    "Claudin 18.2-directed Cytolytic Antibody": ["anticancer"],
    "Glycolipid Disialoganglioside-directed Antibody": ["anticancer"],
    "Lymphocyte Activation Gene-3 Blocker": ["anticancer"],
    "Bispecific gp100 Peptide-HLA-directed CD3 T Cell Engager": ["anticancer"],
    "CD19-directed Chimeric Antigen Receptor": ["anticancer"],
    "Human Immunodeficiency Virus Nucleoside Analog Reverse Transcriptase Inhibitor": ["antiretroviral"],
    "Human Immunodeficiency Virus 1 Non-Nucleoside Analog Reverse Transcriptase Inhibitor": ["antiretroviral"],
    "Human Immunodeficiency Virus Integrase Strand Transfer Inhibitor": ["antiretroviral"],
    "CCR5 Co-receptor Antagonist": ["antiretroviral"],
    "Human Immunodeficiency Virus 1 Capsid Inhibitor": ["antiretroviral"],
    "Human Immunodeficiency Virus 1 Post-attachment Fusion Inhibitor": ["antiretroviral"],
    "Fluoroquinolone Antibacterial": ["antibiotic_chelating"],
    "Quinolone Antimicrobial": ["antibiotic_chelating"],
    "Tetracycline-class Drug": ["antibiotic_chelating"],
    "Tetracycline-class Antibacterial": ["antibiotic_chelating"],
    "Tetracycline-class Antimicrobial": ["antibiotic_chelating"],
    "Penicillin-class Antibacterial": ["antibiotic_other"],
    "Cephalosporin Antibacterial": ["antibiotic_other"],
    "Aminoglycoside Antibacterial": ["antibiotic_other", "nephrotoxic"],
    "Macrolide Antimicrobial": ["antibiotic_other"],
    "Macrolide": ["antibiotic_other"],
    "Macrolide Antibacterial": ["antibiotic_other"],
    "Lincosamide Antibacterial": ["antibiotic_other"],
    "Sulfonamide Antibacterial": ["antibiotic_other"],
    "Sulfonamide Antimicrobial": ["antibiotic_other"],
    "Methylated Sulfonamide Antibacterial": ["antibiotic_other"],
    "Glycopeptide Antibacterial": ["antibiotic_other"],
    "Lipoglycopeptide Antibacterial": ["antibiotic_other"],
    "Lipopeptide Antibacterial": ["antibiotic_other"],
    "Nitrofuran Antibacterial": ["antibiotic_other"],
    "Nitroimidazole Antimicrobial": ["antibiotic_other"],
    "Penem Antibacterial": ["antibiotic_other"],
    "Monobactam Antibacterial": ["antibiotic_other"],
    "Oxazolidinone Antibacterial": ["antibiotic_other"],
    "Polymyxin-class Antibacterial": ["antibiotic_other", "nephrotoxic"],
    "Dihydrofolate Reductase Inhibitor Antibacterial": ["antibiotic_other"],
    "Amphenicol-class Antibacterial": ["antibiotic_other"],
    "Pleuromutilin Antibacterial": ["antibiotic_other"],
    "Triazaacenaphthylene Bacterial Type II Topoisomerase Inhibitor": ["antibiotic_other"],
    "RNA Synthetase Inhibitor Antibacterial": ["antibiotic_other"],
    "beta Lactamase Inhibitor": ["antibiotic_other"],
    "Rifamycin Antibacterial": ["antibiotic_other"],
    "Antimycobacterial": ["antitubercular"],
    "Rifamycin Antimycobacterial": ["antitubercular"],
    "Diarylquinoline Antimycobacterial": ["antitubercular"],
    "Proton Pump Inhibitor": ["ppi_antacid"],
    "Histamine-2 Receptor Antagonist": ["ppi_antacid"],
    "Parenteral Iron Replacement": ["iron_mineral_supplement"],
    "Calcium": ["iron_mineral_supplement"],
    "Potassium Salt": ["iron_mineral_supplement"],
    "Stimulant Laxative": ["laxative_stimulant"],
    "General Anesthetic": ["anaesthesia_surgery"],
    "Nondepolarizing Neuromuscular Blocker": ["anaesthesia_surgery"],
    "Depolarizing Neuromuscular Blocker": ["anaesthesia_surgery"],
    "Neuromuscular Blocker": ["anaesthesia_surgery"],
    "Estrogen": ["hormonal_contraceptive_estrogen"],
    "Progestin": ["hormonal_contraceptive_estrogen"],
    "Progesterone": ["hormonal_contraceptive_estrogen"],
    "Estrogen Agonist/Antagonist": ["hormonal_contraceptive_estrogen"],
    "Progestin-containing Intrauterine System": ["hormonal_contraceptive_estrogen"],
    "Progestin-containing Intrauterine Device": ["hormonal_contraceptive_estrogen"],
    "Progesterone Agonist/Antagonist": ["hormonal_contraceptive_estrogen"],
}

# MoA strings (minus " [MoA]") that add a key regardless of EPC.
MOA_MAP = {
    "HIV Protease Inhibitors": ["antiretroviral"],
    "Vitamin K Antagonists": ["anticoagulant_vka"],
}

# --------------------------------------------------------------------------------------------
# Manual overrides: molecule -> {"add": [...], "remove": [...], "note": "..."}
# Applied after EPC mapping. Every "add" is standard pharmacology (drug label class) or a
# boxed / labelled warning; notes flag the judgement calls.
# --------------------------------------------------------------------------------------------
LABEL_HEPATOTOXIC = "FDA boxed or labelled warning for serious liver injury"
LABEL_NEPHROTOXIC = "FDA boxed or labelled warning for nephrotoxicity"

OVERRIDES = {
    # Anticoagulants / antiplatelets
    "warfarin": {"add": ["anticoagulant_vka"]},
    "acenocoumarol": {"add": ["anticoagulant_vka"], "note": "VKA marketed in India/EU, not US"},
    "phenindione": {"add": ["anticoagulant_vka"]},
    "apixaban": {"add": ["anticoagulant_doac"]},
    "rivaroxaban": {"add": ["anticoagulant_doac"]},
    "edoxaban": {"add": ["anticoagulant_doac"]},
    "dabigatran": {"add": ["anticoagulant_doac"]},
    "fondaparinux": {"add": ["anticoagulant_heparin"], "remove": ["anticoagulant_doac"],
                     "note": "parenteral factor Xa inhibitor grouped with heparin key"},
    "argatroban": {"add": ["anticoagulant_heparin"], "remove": ["anticoagulant_doac"],
                   "note": "parenteral direct thrombin inhibitor grouped with heparin key"},
    "bivalirudin": {"add": ["anticoagulant_heparin"], "remove": ["anticoagulant_doac"],
                    "note": "parenteral direct thrombin inhibitor grouped with heparin key"},
    "desirudin": {"add": ["anticoagulant_heparin"], "remove": ["anticoagulant_doac"],
                  "note": "parenteral direct thrombin inhibitor grouped with heparin key"},
    "lepirudin": {"add": ["anticoagulant_heparin"], "remove": ["anticoagulant_doac"]},
    "heparin": {"add": ["anticoagulant_heparin"]},
    "enoxaparin": {"add": ["anticoagulant_heparin"]},
    "dalteparin": {"add": ["anticoagulant_heparin"]},
    "tinzaparin": {"add": ["anticoagulant_heparin"]},
    "nadroparin": {"add": ["anticoagulant_heparin"]},
    "aspirin": {"add": ["antiplatelet", "nsaid"]},
    "clopidogrel": {"add": ["antiplatelet"]},
    "prasugrel": {"add": ["antiplatelet"]},
    "ticagrelor": {"add": ["antiplatelet"]},
    "ticlopidine": {"add": ["antiplatelet"]},
    "cilostazol": {"add": ["antiplatelet"]},
    "dipyridamole": {"add": ["antiplatelet"]},
    "vorapaxar": {"add": ["antiplatelet"]},
    "eptifibatide": {"add": ["antiplatelet"]},
    "tirofiban": {"add": ["antiplatelet"]},
    "abciximab": {"add": ["antiplatelet"]},
    "cangrelor": {"add": ["antiplatelet"]},
    # NSAIDs not marketed in the US (India/EU)
    "aceclofenac": {"add": ["nsaid", "nephrotoxic"]},
    "nimesulide": {"add": ["nsaid", "nephrotoxic", "hepatotoxic"],
                   "note": "hepatotoxicity is why it was withdrawn/restricted in several countries (EMA 2007/2012 review)"},
    "etoricoxib": {"add": ["nsaid", "nephrotoxic"]},
    "lornoxicam": {"add": ["nsaid", "nephrotoxic"]},
    "dexketoprofen": {"add": ["nsaid", "nephrotoxic"]},
    "aceclofenac sodium": {"add": ["nsaid", "nephrotoxic"]},
    "tenoxicam": {"add": ["nsaid", "nephrotoxic"]},
    "zaltoprofen": {"add": ["nsaid", "nephrotoxic"]},
    "flupirtine": {"add": ["hepatotoxic"], "note": "EMA 2018 withdrawal for liver injury; not an NSAID"},
    "metamizole": {"add": ["nsaid"], "note": "dipyrone; non-opioid analgesic usually grouped with NSAIDs (uncertain fit)"},
    "dipyrone": {"add": ["nsaid"], "note": "non-opioid analgesic usually grouped with NSAIDs (uncertain fit)"},
    "mefenamic acid": {"add": ["nsaid", "nephrotoxic"]},
    "ketorolac": {"add": ["nsaid", "nephrotoxic"]},
    "piroxicam": {"add": ["nsaid", "nephrotoxic"]},
    "diclofenac": {"add": ["nsaid", "nephrotoxic"]},
    "ibuprofen": {"add": ["nsaid", "nephrotoxic"]},
    "naproxen": {"add": ["nsaid", "nephrotoxic"]},
    "celecoxib": {"add": ["nsaid", "nephrotoxic"]},
    "indomethacin": {"add": ["nsaid", "nephrotoxic"]},
    "meloxicam": {"add": ["nsaid", "nephrotoxic"]},
    "etodolac": {"add": ["nsaid", "nephrotoxic"]},
    "ketoprofen": {"add": ["nsaid", "nephrotoxic"]},
    "flurbiprofen": {"add": ["nsaid", "nephrotoxic"]},
    # Diabetes
    "metformin": {"add": ["antidiabetic_other"]},
    "glimepiride": {"add": ["antidiabetic_sulfonylurea"]},
    "gliclazide": {"add": ["antidiabetic_sulfonylurea"], "note": "not US-marketed"},
    "glyburide": {"add": ["antidiabetic_sulfonylurea"]},
    "glipizide": {"add": ["antidiabetic_sulfonylurea"]},
    "tolbutamide": {"add": ["antidiabetic_sulfonylurea"]},
    "chlorpropamide": {"add": ["antidiabetic_sulfonylurea"]},
    "teneligliptin": {"add": ["antidiabetic_other"], "note": "DPP-4 inhibitor (India/Japan)"},
    "vildagliptin": {"add": ["antidiabetic_other"], "note": "DPP-4 inhibitor (EU/India)"},
    "evogliptin": {"add": ["antidiabetic_other"], "note": "DPP-4 inhibitor (India/Korea)"},
    "gemigliptin": {"add": ["antidiabetic_other"]},
    "sitagliptin": {"add": ["antidiabetic_other"]},
    "linagliptin": {"add": ["antidiabetic_other"]},
    "saxagliptin": {"add": ["antidiabetic_other"]},
    "alogliptin": {"add": ["antidiabetic_other"]},
    "voglibose": {"add": ["antidiabetic_other"], "note": "alpha-glucosidase inhibitor (India/Japan)"},
    "acarbose": {"add": ["antidiabetic_other"]},
    "miglitol": {"add": ["antidiabetic_other"]},
    "remogliflozin": {"add": ["antidiabetic_other"], "note": "SGLT2 inhibitor (India)"},
    "remogliflozin etabonate": {"add": ["antidiabetic_other"], "note": "SGLT2 inhibitor (India)"},
    "dapagliflozin": {"add": ["antidiabetic_other"]},
    "empagliflozin": {"add": ["antidiabetic_other"]},
    "canagliflozin": {"add": ["antidiabetic_other"]},
    "pioglitazone": {"add": ["antidiabetic_other"]},
    "repaglinide": {"add": ["antidiabetic_other"]},
    "nateglinide": {"add": ["antidiabetic_other"]},
    "imeglimin": {"add": ["antidiabetic_other"], "note": "glimin-class oral antidiabetic (India/Japan)"},
    "saroglitazar": {"add": ["antidiabetic_other"],
                     "note": "PPAR-alpha/gamma agonist approved in India for diabetic dyslipidaemia; glucose-lowering (judgement call)"},
    "lobeglitazone": {"add": ["antidiabetic_other"]},
    "bromocriptine": {"note": "Cycloset is an antidiabetic but the molecule is mainly dopaminergic; left unmapped"},
    "semaglutide": {"add": ["antidiabetic_other"]},
    "liraglutide": {"add": ["antidiabetic_other"]},
    "dulaglutide": {"add": ["antidiabetic_other"]},
    "exenatide": {"add": ["antidiabetic_other"]},
    "tirzepatide": {"add": ["antidiabetic_other"]},
    # Cardiovascular
    "cilnidipine": {"add": ["antihypertensive"], "note": "dihydropyridine CCB (India/Japan)"},
    "azelnidipine": {"add": ["antihypertensive"]},
    "benidipine": {"add": ["antihypertensive"]},
    "lercanidipine": {"add": ["antihypertensive"]},
    "levamlodipine": {"add": ["antihypertensive"]},
    "moxonidine": {"add": ["antihypertensive"]},
    "metoprolol": {"add": ["antihypertensive"]},
    "amlodipine": {"add": ["antihypertensive"]},
    "telmisartan": {"add": ["antihypertensive", "potassium_sparing"]},
    "olmesartan": {"add": ["antihypertensive", "potassium_sparing"]},
    "losartan": {"add": ["antihypertensive", "potassium_sparing"]},
    "ramipril": {"add": ["antihypertensive", "potassium_sparing"]},
    "perindopril": {"add": ["antihypertensive", "potassium_sparing"]},
    "enalapril": {"add": ["antihypertensive", "potassium_sparing"]},
    "sacubitril": {"add": ["antihypertensive"], "note": "neprilysin inhibitor, only sold with valsartan"},
    "hydralazine": {"add": ["antihypertensive"]},
    "minoxidil": {"add": ["antihypertensive"], "note": "oral form is an antihypertensive; topical (hair) form has little systemic effect"},
    "methyldopa": {"add": ["antihypertensive"]},
    "clonidine": {"add": ["antihypertensive"]},
    "prazosin": {"add": ["antihypertensive"]},
    "torsemide": {"add": ["diuretic_loop_thiazide"]},
    "furosemide": {"add": ["diuretic_loop_thiazide"]},
    "hydrochlorothiazide": {"add": ["diuretic_loop_thiazide", "antihypertensive"]},
    "chlorthalidone": {"add": ["diuretic_loop_thiazide", "antihypertensive"]},
    "indapamide": {"add": ["diuretic_loop_thiazide", "antihypertensive"]},
    "metolazone": {"add": ["diuretic_loop_thiazide", "antihypertensive"]},
    "spironolactone": {"add": ["potassium_sparing"]},
    "eplerenone": {"add": ["potassium_sparing"]},
    "amiloride": {"add": ["potassium_sparing"]},
    "triamterene": {"add": ["potassium_sparing"]},
    "finerenone": {"add": ["potassium_sparing"]},
    "digoxin": {"add": ["cardiac_glycoside"]},
    "digitoxin": {"add": ["cardiac_glycoside"]},
    "amiodarone": {"add": ["antiarrhythmic", "hepatotoxic"], "note": "hepatotoxic: " + LABEL_HEPATOTOXIC},
    "dronedarone": {"add": ["antiarrhythmic"]},
    "flecainide": {"add": ["antiarrhythmic"]},
    "propafenone": {"add": ["antiarrhythmic"]},
    "sotalol": {"add": ["antiarrhythmic", "antihypertensive"]},
    "dofetilide": {"add": ["antiarrhythmic"]},
    "quinidine": {"add": ["antiarrhythmic"]},
    "procainamide": {"add": ["antiarrhythmic"]},
    "disopyramide": {"add": ["antiarrhythmic"]},
    "mexiletine": {"add": ["antiarrhythmic"]},
    "isosorbide mononitrate": {"add": ["nitrate_pde5"]},
    "isosorbide dinitrate": {"add": ["nitrate_pde5"]},
    "nitroglycerin": {"add": ["nitrate_pde5"]},
    "nicorandil": {"add": ["nitrate_pde5"],
                   "note": "K-channel opener with a nitrate moiety; labels contraindicate PDE5 inhibitors (India/EU)"},
    "sildenafil": {"add": ["nitrate_pde5"]},
    "tadalafil": {"add": ["nitrate_pde5"]},
    "vardenafil": {"add": ["nitrate_pde5"]},
    "avanafil": {"add": ["nitrate_pde5"]},
    "udenafil": {"add": ["nitrate_pde5"]},
    "riociguat": {"add": ["nitrate_pde5"],
                  "note": "sGC stimulator; label contraindicates nitrates and PDE5 inhibitors (judgement call)"},
    "atorvastatin": {"add": ["statin"]},
    "rosuvastatin": {"add": ["statin"]},
    "simvastatin": {"add": ["statin"]},
    "pitavastatin": {"add": ["statin"]},
    "pravastatin": {"add": ["statin"]},
    "lovastatin": {"add": ["statin"]},
    "fluvastatin": {"add": ["statin"]},
    # Thyroid
    "levothyroxine": {"add": ["thyroid_hormone"]},
    "liothyronine": {"add": ["thyroid_hormone"]},
    "liotrix": {"add": ["thyroid_hormone"]},
    "thyroid": {"add": ["thyroid_hormone"], "note": "desiccated thyroid (porcine)"},
    "thyroid, porcine": {"add": ["thyroid_hormone"]},
    "methimazole": {"add": ["antithyroid"]},
    "thiamazole": {"add": ["antithyroid"]},
    "carbimazole": {"add": ["antithyroid"], "note": "prodrug of methimazole (India/UK)"},
    "propylthiouracil": {"add": ["antithyroid", "hepatotoxic"], "note": "hepatotoxic: " + LABEL_HEPATOTOXIC},
    # Immunosuppressants
    "cyclosporine": {"add": ["immunosuppressant", "nephrotoxic"], "note": "nephrotoxic: " + LABEL_NEPHROTOXIC},
    "tacrolimus": {"add": ["immunosuppressant", "nephrotoxic"], "note": "nephrotoxic: " + LABEL_NEPHROTOXIC},
    "sirolimus": {"add": ["immunosuppressant"]},
    "everolimus": {"add": ["immunosuppressant", "anticancer"]},
    "mycophenolic acid": {"add": ["immunosuppressant"]},
    "mycophenolate mofetil": {"add": ["immunosuppressant"]},
    "azathioprine": {"add": ["immunosuppressant"]},
    "methotrexate": {"add": ["immunosuppressant", "anticancer", "hepatotoxic", "nephrotoxic"],
                     "note": "hepatotoxic/nephrotoxic: " + LABEL_HEPATOTOXIC},
    "leflunomide": {"add": ["immunosuppressant", "hepatotoxic"], "note": "hepatotoxic: " + LABEL_HEPATOTOXIC},
    "teriflunomide": {"add": ["immunosuppressant", "hepatotoxic"], "note": "hepatotoxic: " + LABEL_HEPATOTOXIC},
    "hydroxychloroquine": {"note": "DMARD/antimalarial; no spec key"},
    "belatacept": {"add": ["immunosuppressant"]},
    "basiliximab": {"add": ["immunosuppressant"]},
    "voclosporin": {"add": ["immunosuppressant"]},
    "pimecrolimus": {"note": "topical calcineurin inhibitor (minimal systemic exposure)"},
    # Psychiatry / CNS
    "lithium carbonate": {"add": ["lithium"]},
    "lithium citrate": {"add": ["lithium"]},
    "lithium": {"add": ["lithium"]},
    "valproic acid": {"add": ["antiepileptic", "hepatotoxic"], "note": "hepatotoxic: " + LABEL_HEPATOTOXIC},
    "divalproex sodium": {"add": ["antiepileptic", "hepatotoxic"]},
    "carbamazepine": {"add": ["antiepileptic"]},
    "oxcarbazepine": {"add": ["antiepileptic"]},
    "eslicarbazepine": {"add": ["antiepileptic"]},
    "phenytoin": {"add": ["antiepileptic"]},
    "fosphenytoin": {"add": ["antiepileptic"]},
    "phenobarbital": {"add": ["antiepileptic", "sedative_hypnotic"]},
    "primidone": {"add": ["antiepileptic"]},
    "levetiracetam": {"add": ["antiepileptic"]},
    "brivaracetam": {"add": ["antiepileptic"]},
    "lamotrigine": {"add": ["antiepileptic"]},
    "topiramate": {"add": ["antiepileptic"]},
    "zonisamide": {"add": ["antiepileptic"]},
    "lacosamide": {"add": ["antiepileptic"]},
    "gabapentin": {"add": ["antiepileptic"]},
    "pregabalin": {"add": ["antiepileptic"]},
    "clobazam": {"add": ["antiepileptic", "sedative_hypnotic"]},
    "clonazepam": {"add": ["antiepileptic", "sedative_hypnotic"]},
    "ethosuximide": {"add": ["antiepileptic"]},
    "felbamate": {"add": ["antiepileptic", "hepatotoxic"], "note": "hepatotoxic: " + LABEL_HEPATOTOXIC},
    "vigabatrin": {"add": ["antiepileptic"]},
    "tiagabine": {"add": ["antiepileptic"]},
    "rufinamide": {"add": ["antiepileptic"]},
    "perampanel": {"add": ["antiepileptic"]},
    "cenobamate": {"add": ["antiepileptic"]},
    "stiripentol": {"add": ["antiepileptic"]},
    "cannabidiol": {"add": ["antiepileptic"]},
    "midazolam": {"add": ["sedative_hypnotic", "anaesthesia_surgery"]},
    "diazepam": {"add": ["sedative_hypnotic"]},
    "lorazepam": {"add": ["sedative_hypnotic"]},
    "alprazolam": {"add": ["sedative_hypnotic"]},
    "chlordiazepoxide": {"add": ["sedative_hypnotic"]},
    "nitrazepam": {"add": ["sedative_hypnotic"], "note": "not US-marketed"},
    "etizolam": {"add": ["sedative_hypnotic"], "note": "thienodiazepine (India/Japan)"},
    "zolpidem": {"add": ["sedative_hypnotic"]},
    "zaleplon": {"add": ["sedative_hypnotic"]},
    "eszopiclone": {"add": ["sedative_hypnotic"]},
    "zopiclone": {"add": ["sedative_hypnotic"], "note": "not US-marketed"},
    "suvorexant": {"add": ["sedative_hypnotic"]},
    "lemborexant": {"add": ["sedative_hypnotic"]},
    "daridorexant": {"add": ["sedative_hypnotic"]},
    "ramelteon": {"add": ["sedative_hypnotic"]},
    "sodium oxybate": {"add": ["sedative_hypnotic"]},
    "meprobamate": {"add": ["sedative_hypnotic"]},
    "butalbital": {"add": ["sedative_hypnotic"]},
    "fluoxetine": {"add": ["antidepressant_ssri_snri"]},
    "sertraline": {"add": ["antidepressant_ssri_snri"]},
    "paroxetine": {"add": ["antidepressant_ssri_snri"]},
    "citalopram": {"add": ["antidepressant_ssri_snri"]},
    "escitalopram": {"add": ["antidepressant_ssri_snri"]},
    "fluvoxamine": {"add": ["antidepressant_ssri_snri"]},
    "venlafaxine": {"add": ["antidepressant_ssri_snri"]},
    "desvenlafaxine": {"add": ["antidepressant_ssri_snri"]},
    "duloxetine": {"add": ["antidepressant_ssri_snri"]},
    "milnacipran": {"add": ["antidepressant_ssri_snri"]},
    "levomilnacipran": {"add": ["antidepressant_ssri_snri"]},
    "vilazodone": {"add": ["antidepressant_ssri_snri"]},
    "vortioxetine": {"add": ["antidepressant_ssri_snri"]},
    "dapoxetine": {"add": ["antidepressant_ssri_snri"], "note": "short-acting SSRI sold for premature ejaculation (India/EU)"},
    "phenelzine": {"add": ["antidepressant_maoi"]},
    "tranylcypromine": {"add": ["antidepressant_maoi"]},
    "isocarboxazid": {"add": ["antidepressant_maoi"]},
    "selegiline": {"add": ["antidepressant_maoi"]},
    "moclobemide": {"add": ["antidepressant_maoi"], "note": "reversible MAO-A inhibitor (not US-marketed)"},
    "amitriptyline": {"add": ["antidepressant_tca"]},
    "nortriptyline": {"add": ["antidepressant_tca"]},
    "imipramine": {"add": ["antidepressant_tca"]},
    "clomipramine": {"add": ["antidepressant_tca"]},
    "desipramine": {"add": ["antidepressant_tca"]},
    "doxepin": {"add": ["antidepressant_tca"]},
    "trimipramine": {"add": ["antidepressant_tca"]},
    "protriptyline": {"add": ["antidepressant_tca"]},
    "amoxapine": {"add": ["antidepressant_tca"]},
    "dosulepin": {"add": ["antidepressant_tca"], "note": "dothiepin (India/UK)"},
    "agomelatine": {"add": ["hepatotoxic"], "note": "EU SmPC requires liver-function monitoring; antidepressant with no matching spec key"},
    "olanzapine": {"add": ["antipsychotic"]},
    "risperidone": {"add": ["antipsychotic"]},
    "paliperidone": {"add": ["antipsychotic"]},
    "quetiapine": {"add": ["antipsychotic"]},
    "aripiprazole": {"add": ["antipsychotic"]},
    "clozapine": {"add": ["antipsychotic"]},
    "haloperidol": {"add": ["antipsychotic"]},
    "chlorpromazine": {"add": ["antipsychotic"]},
    "fluphenazine": {"add": ["antipsychotic"]},
    "perphenazine": {"add": ["antipsychotic"]},
    "trifluoperazine": {"add": ["antipsychotic"]},
    "thioridazine": {"add": ["antipsychotic"]},
    "pimozide": {"add": ["antipsychotic"]},
    "loxapine": {"add": ["antipsychotic"]},
    "lurasidone": {"add": ["antipsychotic"]},
    "ziprasidone": {"add": ["antipsychotic"]},
    "asenapine": {"add": ["antipsychotic"]},
    "iloperidone": {"add": ["antipsychotic"]},
    "brexpiprazole": {"add": ["antipsychotic"]},
    "cariprazine": {"add": ["antipsychotic"]},
    "levosulpiride": {"add": ["antipsychotic"],
                      "note": "D2-antagonist benzamide (S-sulpiride); in India mostly used as a prokinetic (judgement call)"},
    "melitracen": {"add": ["antidepressant_tca"], "note": "tricyclic antidepressant sold with flupentixol (India)"},
    "diacerein": {"add": ["hepatotoxic"], "note": "EMA 2014 restriction for severe diarrhoea and liver effects"},
    "cyproterone": {"add": ["hormonal_contraceptive_estrogen", "hepatotoxic"],
                    "note": "progestogenic antiandrogen used with ethinylestradiol; SmPC hepatotoxicity warning (high dose)"},
    "allylestrenol": {"add": ["hormonal_contraceptive_estrogen"], "note": "progestogen (India)"},
    "s-metoprolol": {"add": ["antihypertensive"], "note": "single enantiomer of metoprolol (India)"},
    "efonidipine": {"add": ["antihypertensive"], "note": "dihydropyridine CCB (India/Japan)"},
    "furazolidone": {"add": ["antibiotic_other"]},
    "nalidixic acid": {"add": ["antibiotic_chelating"], "note": "first-generation quinolone"},
    "teicoplanin": {"add": ["antibiotic_other"]},
    "dicloxacillin": {"add": ["antibiotic_other"]},
    "amisulpride": {"add": ["antipsychotic"], "note": "not US-marketed as oral antipsychotic (IV antiemetic only)"},
    "sulpiride": {"add": ["antipsychotic"]},
    "flupentixol": {"add": ["antipsychotic"], "note": "not US-marketed"},
    "flupenthixol": {"add": ["antipsychotic"], "note": "not US-marketed"},
    "zuclopenthixol": {"add": ["antipsychotic"]},
    "blonanserin": {"add": ["antipsychotic"]},
    "prochlorperazine": {"add": ["antipsychotic"], "note": "phenothiazine mainly used as antiemetic"},
    # Opioids
    "loperamide": {"remove": ["opioid"], "note": "peripheral opioid antidiarrhoeal; opioid key removed"},
    "eluxadoline": {"remove": ["opioid"]},
    "difelikefalin": {"remove": ["opioid"]},
    "tramadol": {"add": ["opioid"]},
    "tapentadol": {"add": ["opioid"]},
    "morphine": {"add": ["opioid"]},
    "codeine": {"add": ["opioid"]},
    "fentanyl": {"add": ["opioid", "anaesthesia_surgery"]},
    "buprenorphine": {"add": ["opioid"]},
    "pentazocine": {"add": ["opioid"]},
    "butorphanol": {"add": ["opioid"]},
    "nalbuphine": {"add": ["opioid"]},
    "dextropropoxyphene": {"add": ["opioid"]},
    "hydrocodone": {"add": ["opioid"]},
    "oxycodone": {"add": ["opioid"]},
    "methadone": {"add": ["opioid"]},
    "meperidine": {"add": ["opioid"]},
    "alfentanil": {"add": ["opioid", "anaesthesia_surgery"]},
    "sufentanil": {"add": ["opioid", "anaesthesia_surgery"]},
    "remifentanil": {"add": ["opioid", "anaesthesia_surgery"]},
    # Oncology / hormonal
    "tamoxifen": {"add": ["anticancer", "hormonal_contraceptive_estrogen"]},
    "toremifene": {"add": ["anticancer", "hormonal_contraceptive_estrogen"]},
    "raloxifene": {"add": ["hormonal_contraceptive_estrogen"]},
    "clomiphene": {"add": ["hormonal_contraceptive_estrogen"], "remove": ["anticancer"]},
    "ormeloxifene": {"add": ["hormonal_contraceptive_estrogen"], "note": "centchroman, SERM oral contraceptive (India)"},
    "dydrogesterone": {"add": ["hormonal_contraceptive_estrogen"], "note": "progestogen (HRT/pregnancy support; not US-marketed)"},
    "tibolone": {"add": ["hormonal_contraceptive_estrogen"], "note": "HRT (not US-marketed)"},
    "ethinyl estradiol": {"add": ["hormonal_contraceptive_estrogen"]},
    "levonorgestrel": {"add": ["hormonal_contraceptive_estrogen"]},
    "desogestrel": {"add": ["hormonal_contraceptive_estrogen"]},
    "drospirenone": {"add": ["hormonal_contraceptive_estrogen"]},
    "norethindrone": {"add": ["hormonal_contraceptive_estrogen"]},
    "ulipristal": {"add": ["hormonal_contraceptive_estrogen"]},
    "estradiol": {"add": ["hormonal_contraceptive_estrogen"]},
    "conjugated estrogens": {"add": ["hormonal_contraceptive_estrogen"]},
    "estrogens, conjugated": {"add": ["hormonal_contraceptive_estrogen"]},
    "medroxyprogesterone": {"add": ["hormonal_contraceptive_estrogen"]},
    "bicalutamide": {"add": ["anticancer"]},
    "flutamide": {"add": ["anticancer", "hepatotoxic"], "note": "hepatotoxic: " + LABEL_HEPATOTOXIC},
    "clascoterone": {"remove": ["anticancer"], "note": "topical acne androgen-receptor inhibitor"},
    "nintedanib": {"remove": ["anticancer"], "note": "kinase inhibitor used for pulmonary fibrosis (also used in NSCLC outside US)"},
    "fostamatinib": {"remove": ["anticancer"], "note": "kinase inhibitor for immune thrombocytopenia"},
    "netarsudil": {"remove": ["anticancer"]},
    "lonafarnib": {"remove": ["anticancer"]},
    "colchicine": {"remove": ["anticancer"]},
    "fluorouracil": {"add": ["anticancer"]},
    "mercaptopurine": {"add": ["anticancer", "immunosuppressant"]},
    "hydroxyurea": {"add": ["anticancer"]},
    "imatinib": {"add": ["anticancer"]},
    "capecitabine": {"add": ["anticancer"]},
    "cyclophosphamide": {"add": ["anticancer", "immunosuppressant"]},
    "cisplatin": {"add": ["anticancer", "nephrotoxic"], "note": "nephrotoxic: " + LABEL_NEPHROTOXIC},
    "ifosfamide": {"add": ["anticancer", "nephrotoxic"], "note": "nephrotoxic: " + LABEL_NEPHROTOXIC},
    "letrozole": {"add": ["anticancer"]},
    "anastrozole": {"add": ["anticancer"]},
    "lapatinib": {"add": ["anticancer", "hepatotoxic"], "note": "hepatotoxic: " + LABEL_HEPATOTOXIC},
    "pazopanib": {"add": ["anticancer", "hepatotoxic"], "note": "hepatotoxic: " + LABEL_HEPATOTOXIC},
    "regorafenib": {"add": ["anticancer", "hepatotoxic"], "note": "hepatotoxic: " + LABEL_HEPATOTOXIC},
    "sunitinib": {"add": ["anticancer", "hepatotoxic"], "note": "hepatotoxic: " + LABEL_HEPATOTOXIC},
    "idelalisib": {"add": ["anticancer", "hepatotoxic"], "note": "hepatotoxic: " + LABEL_HEPATOTOXIC},
    "pexidartinib": {"add": ["anticancer", "hepatotoxic"], "note": "hepatotoxic: " + LABEL_HEPATOTOXIC},
    "arsenic trioxide": {"add": ["anticancer"]},
    "rituximab": {"add": ["anticancer", "immunosuppressant"]},
    "trastuzumab": {"add": ["anticancer"]},
    "bevacizumab": {"add": ["anticancer"]},
    "thalidomide": {"add": ["anticancer"]},
    "lenalidomide": {"add": ["anticancer"]},
    "temozolomide": {"add": ["anticancer"]},
    "abiraterone": {"add": ["anticancer"]},
    "enzalutamide": {"add": ["anticancer"]},
    "leuprolide": {"note": "GnRH agonist (prostate cancer, endometriosis); no spec key"},
    # Antiretrovirals (+ boosters)
    "ritonavir": {"add": ["antiretroviral"]},
    "cobicistat": {"add": ["antiretroviral"], "note": "pharmacokinetic booster used only with HIV drugs"},
    "lopinavir": {"add": ["antiretroviral"]},
    "atazanavir": {"add": ["antiretroviral"]},
    "darunavir": {"add": ["antiretroviral"]},
    "dolutegravir": {"add": ["antiretroviral"]},
    "efavirenz": {"add": ["antiretroviral"]},
    "nevirapine": {"add": ["antiretroviral", "hepatotoxic"], "note": "hepatotoxic: " + LABEL_HEPATOTOXIC},
    "tipranavir": {"add": ["antiretroviral", "hepatotoxic"], "note": "hepatotoxic: " + LABEL_HEPATOTOXIC},
    "maraviroc": {"add": ["antiretroviral", "hepatotoxic"], "note": "hepatotoxic: " + LABEL_HEPATOTOXIC},
    "zidovudine": {"add": ["antiretroviral"]},
    "lamivudine": {"add": ["antiretroviral"]},
    "tenofovir": {"add": ["antiretroviral", "nephrotoxic"],
                  "note": "also used for hepatitis B; nephrotoxic: labelled renal impairment/Fanconi warning (TDF)"},
    "abacavir": {"add": ["antiretroviral"]},
    "emtricitabine": {"add": ["antiretroviral"]},
    "raltegravir": {"add": ["antiretroviral"]},
    "nirmatrelvir": {"note": "SARS-CoV-2 protease inhibitor (co-packaged with ritonavir)"},
    # Anti-infectives
    "ciprofloxacin": {"add": ["antibiotic_chelating"]},
    "levofloxacin": {"add": ["antibiotic_chelating"]},
    "ofloxacin": {"add": ["antibiotic_chelating"]},
    "moxifloxacin": {"add": ["antibiotic_chelating"]},
    "norfloxacin": {"add": ["antibiotic_chelating"]},
    "prulifloxacin": {"add": ["antibiotic_chelating"]},
    "sparfloxacin": {"add": ["antibiotic_chelating"]},
    "gemifloxacin": {"add": ["antibiotic_chelating"]},
    "nadifloxacin": {"add": ["antibiotic_chelating"], "note": "topical fluoroquinolone"},
    "doxycycline": {"add": ["antibiotic_chelating"]},
    "minocycline": {"add": ["antibiotic_chelating"]},
    "tetracycline": {"add": ["antibiotic_chelating"]},
    "faropenem": {"add": ["antibiotic_other"], "note": "oral penem (India)"},
    "ornidazole": {"add": ["antibiotic_other"], "note": "nitroimidazole (India/EU)"},
    "satranidazole": {"add": ["antibiotic_other"], "note": "nitroimidazole (India)"},
    "secnidazole": {"add": ["antibiotic_other"]},
    "tinidazole": {"add": ["antibiotic_other"]},
    "metronidazole": {"add": ["antibiotic_other"]},
    "roxithromycin": {"add": ["antibiotic_other"], "note": "macrolide (not US-marketed)"},
    "azithromycin": {"add": ["antibiotic_other"]},
    "clarithromycin": {"add": ["antibiotic_other"]},
    "erythromycin": {"add": ["antibiotic_other"]},
    "cefpodoxime": {"add": ["antibiotic_other"]},
    "cefixime": {"add": ["antibiotic_other"]},
    "cefuroxime": {"add": ["antibiotic_other"]},
    "ceftriaxone": {"add": ["antibiotic_other"]},
    "cefoperazone": {"add": ["antibiotic_other"]},
    "amoxicillin": {"add": ["antibiotic_other"]},
    "ampicillin": {"add": ["antibiotic_other"]},
    "cloxacillin": {"add": ["antibiotic_other"]},
    "flucloxacillin": {"add": ["antibiotic_other"]},
    "clavulanate": {"add": ["antibiotic_other"]},
    "sulbactam": {"add": ["antibiotic_other"]},
    "tazobactam": {"add": ["antibiotic_other"]},
    "linezolid": {"add": ["antibiotic_other"]},
    "nitrofurantoin": {"add": ["antibiotic_other"]},
    "sulfamethoxazole": {"add": ["antibiotic_other"]},
    "trimethoprim": {"add": ["antibiotic_other"]},
    "vancomycin": {"add": ["antibiotic_other", "nephrotoxic"], "note": "nephrotoxic: " + LABEL_NEPHROTOXIC},
    "amikacin": {"add": ["antibiotic_other", "nephrotoxic"]},
    "gentamicin": {"add": ["antibiotic_other", "nephrotoxic"]},
    "tobramycin": {"add": ["antibiotic_other", "nephrotoxic"]},
    "streptomycin": {"add": ["antibiotic_other", "antitubercular", "nephrotoxic"]},
    "polymyxin b": {"add": ["antibiotic_other", "nephrotoxic"]},
    "colistimethate": {"add": ["antibiotic_other", "nephrotoxic"]},
    "colistin": {"add": ["antibiotic_other", "nephrotoxic"]},
    "clindamycin": {"add": ["antibiotic_other"]},
    "rifaximin": {"add": ["antibiotic_other"], "remove": ["antitubercular"]},
    "isoniazid": {"add": ["antitubercular", "hepatotoxic"], "note": "hepatotoxic: " + LABEL_HEPATOTOXIC},
    "rifampin": {"add": ["antitubercular", "hepatotoxic"]},
    "rifabutin": {"add": ["antitubercular"]},
    "rifapentine": {"add": ["antitubercular"]},
    "pyrazinamide": {"add": ["antitubercular", "hepatotoxic"]},
    "ethambutol": {"add": ["antitubercular"]},
    "bedaquiline": {"add": ["antitubercular"]},
    "delamanid": {"add": ["antitubercular"], "note": "not US-marketed"},
    "pretomanid": {"add": ["antitubercular"]},
    "cycloserine": {"add": ["antitubercular"]},
    "ethionamide": {"add": ["antitubercular"]},
    "aminosalicylic acid": {"add": ["antitubercular"]},
    "dapsone": {"note": "antileprosy sulfone; no spec key"},
    "clofazimine": {"note": "antileprosy; no spec key"},
    "ketoconazole": {"add": ["hepatotoxic"], "note": "oral form: " + LABEL_HEPATOTOXIC},
    "terbinafine": {"add": ["hepatotoxic"], "note": "oral form: labelled liver failure warning"},
    "amphotericin b": {"add": ["nephrotoxic"], "note": "nephrotoxic: " + LABEL_NEPHROTOXIC},
    "cidofovir": {"add": ["nephrotoxic"], "note": "nephrotoxic: " + LABEL_NEPHROTOXIC},
    "foscarnet": {"add": ["nephrotoxic"], "note": "nephrotoxic: " + LABEL_NEPHROTOXIC},
    "pentamidine": {"add": ["nephrotoxic"]},
    "zoledronic acid": {"add": ["nephrotoxic"], "note": "labelled renal toxicity warning"},
    # Hepatotoxic (boxed warnings)
    "acetaminophen": {"add": ["hepatotoxic"], "note": "dose-related hepatotoxicity (US boxed warning on Rx products)"},
    "bosentan": {"add": ["hepatotoxic"], "note": LABEL_HEPATOTOXIC},
    "dantrolene": {"add": ["hepatotoxic"], "note": "oral form: " + LABEL_HEPATOTOXIC},
    "tolvaptan": {"add": ["hepatotoxic"], "note": LABEL_HEPATOTOXIC},
    "lomitapide": {"add": ["hepatotoxic"], "note": LABEL_HEPATOTOXIC},
    "mipomersen": {"add": ["hepatotoxic"], "note": LABEL_HEPATOTOXIC},
    "deferasirox": {"add": ["hepatotoxic", "nephrotoxic"], "note": "boxed warning: renal and hepatic failure"},
    "obeticholic acid": {"add": ["hepatotoxic"], "note": LABEL_HEPATOTOXIC},
    # GI / acid
    "omeprazole": {"add": ["ppi_antacid"]},
    "esomeprazole": {"add": ["ppi_antacid"]},
    "pantoprazole": {"add": ["ppi_antacid"]},
    "rabeprazole": {"add": ["ppi_antacid"]},
    "lansoprazole": {"add": ["ppi_antacid"]},
    "dexlansoprazole": {"add": ["ppi_antacid"]},
    "ilaprazole": {"add": ["ppi_antacid"], "note": "PPI (India/China/Korea)"},
    "vonoprazan": {"add": ["ppi_antacid"], "note": "potassium-competitive acid blocker"},
    "famotidine": {"add": ["ppi_antacid"]},
    "ranitidine": {"add": ["ppi_antacid"]},
    "cimetidine": {"add": ["ppi_antacid"]},
    "nizatidine": {"add": ["ppi_antacid"]},
    "aluminum hydroxide": {"add": ["ppi_antacid"]},
    "magnesium hydroxide": {"add": ["ppi_antacid"]},
    "magnesium trisilicate": {"add": ["ppi_antacid"]},
    "magnesium carbonate": {"add": ["ppi_antacid"]},
    "calcium carbonate": {"add": ["ppi_antacid", "iron_mineral_supplement"]},
    "sodium bicarbonate": {"add": ["ppi_antacid"]},
    "magaldrate": {"add": ["ppi_antacid"]},
    "sucralfate": {"add": ["ppi_antacid"], "note": "aluminium complex; binds other drugs (judgement call)"},
    "bisacodyl": {"add": ["laxative_stimulant"]},
    "sennosides": {"add": ["laxative_stimulant"]},
    "sodium picosulfate": {"add": ["laxative_stimulant"]},
    "cascara sagrada": {"add": ["laxative_stimulant"]},
    "castor oil": {"add": ["laxative_stimulant"]},
    # Minerals
    "ferrous sulfate": {"add": ["iron_mineral_supplement"]},
    "ferrous fumarate": {"add": ["iron_mineral_supplement"]},
    "ferrous gluconate": {"add": ["iron_mineral_supplement"]},
    "ferrous ascorbate": {"add": ["iron_mineral_supplement"]},
    "ferrous bisglycinate": {"add": ["iron_mineral_supplement"]},
    "ferric carboxymaltose": {"add": ["iron_mineral_supplement"]},
    "ferric ammonium citrate": {"add": ["iron_mineral_supplement"]},
    "ferric pyrophosphate": {"add": ["iron_mineral_supplement"]},
    "iron sucrose": {"add": ["iron_mineral_supplement"]},
    "iron dextran": {"add": ["iron_mineral_supplement"]},
    "iron polymaltose": {"add": ["iron_mineral_supplement"]},
    "ferric hydroxide polymaltose": {"add": ["iron_mineral_supplement"]},
    "iron": {"add": ["iron_mineral_supplement"]},
    "carbonyl iron": {"add": ["iron_mineral_supplement"]},
    "polysaccharide iron complex": {"add": ["iron_mineral_supplement"]},
    "sodium feredetate": {"add": ["iron_mineral_supplement"]},
    "ferrous salts": {"add": ["iron_mineral_supplement"]},
    "calcium citrate": {"add": ["iron_mineral_supplement"]},
    "calcium gluconate": {"add": ["iron_mineral_supplement"]},
    "calcium lactate": {"add": ["iron_mineral_supplement"]},
    "calcium citrate malate": {"add": ["iron_mineral_supplement"]},
    "zinc sulfate": {"add": ["iron_mineral_supplement"]},
    "zinc gluconate": {"add": ["iron_mineral_supplement"]},
    "zinc acetate": {"add": ["iron_mineral_supplement"]},
    "magnesium oxide": {"add": ["iron_mineral_supplement"]},
    "magnesium sulfate": {"add": ["iron_mineral_supplement"]},
    "potassium chloride": {"add": ["iron_mineral_supplement"]},
    "potassium citrate": {"add": ["iron_mineral_supplement"]},
    # Methylxanthines
    "theophylline": {"add": ["theophylline"]},
    "aminophylline": {"add": ["theophylline"]},
    "oxtriphylline": {"add": ["theophylline"]},
    "doxofylline": {"add": ["theophylline"],
                    "note": "methylxanthine bronchodilator (India/EU); grouped with theophylline key (judgement call)"},
    "acebrophylline": {"add": ["theophylline"],
                       "note": "ambroxol salt of theophylline-7-acetic acid (India); grouped with theophylline key (judgement call)"},
    "etofylline": {"add": ["theophylline"], "note": "theophylline derivative (India, in 'Deriphylline'); judgement call"},
    # Anaesthesia
    "propofol": {"add": ["anaesthesia_surgery", "sedative_hypnotic"]},
    "ketamine": {"add": ["anaesthesia_surgery"]},
    "esketamine": {"add": ["anaesthesia_surgery"], "note": "nasal antidepressant form; anaesthetic class (judgement call)"},
    "etomidate": {"add": ["anaesthesia_surgery"]},
    "thiopental": {"add": ["anaesthesia_surgery", "sedative_hypnotic"]},
    "methohexital": {"add": ["anaesthesia_surgery", "sedative_hypnotic"]},
    "sevoflurane": {"add": ["anaesthesia_surgery"]},
    "isoflurane": {"add": ["anaesthesia_surgery"]},
    "desflurane": {"add": ["anaesthesia_surgery"]},
    "halothane": {"add": ["anaesthesia_surgery"]},
    "nitrous oxide": {"add": ["anaesthesia_surgery"]},
    "dexmedetomidine": {"add": ["anaesthesia_surgery", "sedative_hypnotic"]},
    "remimazolam": {"add": ["anaesthesia_surgery", "sedative_hypnotic"]},
    "succinylcholine": {"add": ["anaesthesia_surgery"]},
    "vecuronium": {"add": ["anaesthesia_surgery"]},
    "atracurium": {"add": ["anaesthesia_surgery"]},
    "rocuronium": {"add": ["anaesthesia_surgery"]},
    "cisatracurium": {"add": ["anaesthesia_surgery"]},
    # Corticosteroids not in US
    "deflazacort": {"add": ["corticosteroid"]},
    "prednisolone": {"add": ["corticosteroid"]},
    "methylprednisolone": {"add": ["corticosteroid"]},
    "dexamethasone": {"add": ["corticosteroid"]},
    "betamethasone": {"add": ["corticosteroid"]},
    "hydrocortisone": {"add": ["corticosteroid"]},
    "budesonide": {"add": ["corticosteroid"]},
    "fluticasone": {"add": ["corticosteroid"]},
    "mometasone": {"add": ["corticosteroid"]},
    "clobetasol": {"add": ["corticosteroid"]},
    "beclomethasone": {"add": ["corticosteroid"]},
    "ciclesonide": {"add": ["corticosteroid"]},
    "triamcinolone": {"add": ["corticosteroid"]},
    "fludrocortisone": {"add": ["corticosteroid"]},
    "prednisone": {"add": ["corticosteroid"]},
}

# --------------------------------------------------------------------------------------------
# CYP / P-gp substrates named by FDA. The current FDA table is parsed at build time from
# fda.gov (healthcare-professionals examples table); these are the FDA lists that are not in the
# current page and were copied from FDA's 2006 "Table of Substrates, Inhibitors and Inducers"
# (snapshot captured 2011-01-03) and from FDA's current index-substrate table.
# --------------------------------------------------------------------------------------------
FDA_2006_URL = ("https://www.fda.gov/Drugs/DevelopmentApprovalProcess/DevelopmentResources/"
                "DrugInteractionsLabeling/ucm093664.htm (2006 version; copy at "
                "https://courses.washington.edu/medch527/PDFs/Literature/527_fdatable.pdf)")
FDA_INDEX_URL = ("https://www.fda.gov/drugs/drug-interactions-labeling/"
                 "drug-development-and-drug-interactions-table-substrates-inhibitors-and-inducers")
FDA_HCP_URL = ("https://www.fda.gov/drugs/drug-interactions-labeling/"
               "healthcare-professionals-fdas-examples-drugs-interact-cyp-enzymes-and-transporter-systems")

FDA_LEGACY_SUBSTRATES = [
    # (molecule, key, category, source)
    # Table 7 (2006): CYP3A substrates with narrow therapeutic range (US-available ones)
    *[(m, "cyp3a4_substrate_narrow", "NTI (FDA 2006 Table 7)", FDA_2006_URL) for m in
      ["alfentanil", "cyclosporine", "dihydroergotamine", "ergotamine", "fentanyl", "pimozide",
       "quinidine", "sirolimus", "tacrolimus"]],
    # Table 7 (2006): sensitive CYP3A substrates not in the current HCP table
    *[(m, "cyp3a4_substrate_narrow", "sensitive (FDA 2006 Table 7)", FDA_2006_URL) for m in
      ["fluticasone"]],
    # Table 8 (2006): narrow therapeutic range for other CYPs
    ("theophylline", "cyp1a2_substrate", "NTI (FDA 2006 Table 8)", FDA_2006_URL),
    ("tizanidine", "cyp1a2_substrate", "NTI (FDA 2006 Table 8)", FDA_2006_URL),
    ("warfarin", "cyp2c9_substrate", "NTI (FDA 2006 Table 8)", FDA_2006_URL),
    ("phenytoin", "cyp2c9_substrate", "NTI (FDA 2006 Table 8)", FDA_2006_URL),
    ("thioridazine", "cyp2d6_substrate", "NTI (FDA 2006 Table 8)", FDA_2006_URL),
    # Table 11 (2006): P-gp (ABCB1) substrates
    *[(m, "pgp_substrate", "P-gp substrate (FDA 2006 Table 11)", FDA_2006_URL) for m in
      ["digoxin", "fexofenadine", "indinavir", "vincristine", "colchicine", "topotecan", "paclitaxel"]],
    # Current index-substrate tables (in vitro/clinical P-gp substrates)
    *[(m, "pgp_substrate", "P-gp substrate (FDA index table)", FDA_INDEX_URL) for m in
      ["digoxin", "fexofenadine", "loperamide", "quinidine", "talinolol", "vinblastine"]],
    *[(m, "cyp1a2_substrate", "sensitive index substrate (FDA index table)", FDA_INDEX_URL) for m in
      ["caffeine", "tizanidine"]],
    *[(m, "cyp2c9_substrate", "index substrate (FDA index table)", FDA_INDEX_URL) for m in
      ["tolbutamide", "warfarin"]],
    *[(m, "cyp2d6_substrate", "sensitive index substrate (FDA index table)", FDA_INDEX_URL) for m in
      ["desipramine", "dextromethorphan", "nebivolol"]],
    *[(m, "cyp3a4_substrate_narrow", "sensitive index substrate (FDA index table)", FDA_INDEX_URL) for m in
      ["midazolam", "triazolam"]],
    # HCP table footnote 1: prodrugs that are P-gp substrates
    *[(m, "pgp_substrate", "P-gp substrate prodrug (FDA HCP table footnote 1)", FDA_HCP_URL) for m in
      ["adefovir", "oseltamivir", "tenofovir"]],
]

# Names in the FDA HCP table that need mapping to a molecule key.
FDA_NAME_FIX = {
    "dabigatran etexilate": "dabigatran",
    "r-venlafaxine": "venlafaxine",
    "s-venlafaxine": "venlafaxine",
    "s-mephenytoin": "mephenytoin",
    "oseltamivir carboxylate": "oseltamivir",
    "penicillin g": "penicillin g",
}

# --------------------------------------------------------------------------------------------
# NLEM 2022 rows that are devices, blood components or fluids, not molecules.
# --------------------------------------------------------------------------------------------
NLEM_NON_MOLECULES = {
    "condom", "iud containing copper", "hormone releasing iud", "haemodialysis fluid",
    "peritoneal dialysis solution", "whole blood", "red blood cells/ packed rbcs",
    "fresh frozen plasma", "cryoprecipitate", "platelet rich plasma/ platelet concentrates",
    "water for injection", "surfactant",
}
